### ISSUE TITLE
enable IPv6 support for provider #IPv6DualStack

### ISSUE THREAD

**Issue by andy108369** [akash-network/support#100]
I've ran the nym-mixnode as PoC

- https://twitter.com/andy83482/status/1665093815290437635
- IPv6 https://twitter.com/andy83482/status/1665348733796511747
- SDL https://gist.github.com/andy108369/ef23ff0fe5caf2e12b1b41a99e812294

Here is how I've enabled the IPv6 on my provider:

----
I've just enabled the IPv6 on my Akash provider (`provider.akash.pro` and it works.
However, with the manual netpol change required to allow the IPv6 Egress, and also Service kind of resource needs to be updated to accept the Ingress over IPv6. See below.

To enable it one needs to do the following:
* 1. Ensure host supports IPv6

```
# ls -la /proc/net/if_inet6
-r--r--r-- 1 root root 0 Jun  4 06:03 /proc/net/if_inet6

# sysctl net.ipv6.conf.all.disable_ipv6 net.ipv6.conf.default.disable_ipv6 net.ipv6.conf.lo.disable_ipv6 net.ipv6.conf.all.forwarding net.ipv6.conf.default.forwarding
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
net.ipv6.conf.all.forwarding = 1
net.ipv6.conf.default.forwarding = 1
```

* 2. Update the netplan config to enable IPv6

> `2a01:4f9:6a:55d0::/64` -- from Hetzner I am using

add to the netplan config:

```
# cat /etc/netplan/01.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
      dhcp4-overrides:
        use-domains: false
      # disable accept-ra, otherwise it will bring search domains to your /etc/resolv.conf
      # refs [https://bugs.launchpad.net/netplan/+bug/1858503](https://bugs.launchpad.net/netplan/+bug/1858503)
      accept-ra: false
      dhcp6: false
      addresses: 
        - 2a01:4f9:6a:55d0::/64
      gateway6: fe80::1
      routes:
      - to: ::/0
        via: fe80::1
        on-link: true
```

* 3. Add `enable_dual_stack_networks: true` to `kubespray/inventory/akash/group_vars/k8s_cluster/k8s-cluster.yml`

* 4. Add `nat_outgoing_ipv6: true` to `inventory/akash/group_vars/k8s_cluster/k8s-net-calico.yml`

* 5. Kubespray the cluster

Apply `facts.yml`, `upgrade-cluster.yml` and `cluster.yml` playbooks in this order.

----

New deployments (or the ones which had their manifest updated) will get the ipv6 address.

However, this requires updating the netpol egress to support the `::/0` IPV6 CIDR for them to access the Egress, e.g.

```
kubectl -n $ns patch netpol akash-deployment-restrictions --type='json' -p='[{"op": "add", "path": "/spec/egress/-", "value": {"to": [{"ipBlock": {"cidr": "::/0"}}]}}]'
```

To accept the Ingress over IPv6 the service needs to be patched as follows:

```
kubectl patch svc mixnode-np -n $ns --type='json' -p='[
  {"op": "replace", "path": "/spec/ipFamilyPolicy", "value": "PreferDualStack"},
  {"op": "replace", "path": "/spec/ipFamilies", "value": ["IPv4", "IPv6"]}
]'
```

## Test IPv6: Egress

```
root@node1:~# kubectl run  -it --rm  wget --image=cirrusci/wget -- sh
If you don't see a command prompt, try pressing enter.
/ # wget -6 google.com
--2023-06-04 13:36:04--  http://google.com/
Resolving google.com... 2a00:1450:400f:80a::200e
Connecting to google.com|2a00:1450:400f:80a::200e|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.com/ [following]
--2023-06-04 13:36:04--  http://www.google.com/
Resolving www.google.com... 2a00:1450:400f:801::2004
Connecting to www.google.com|2a00:1450:400f:801::2004|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'index.html'

index.html                                 [ <=>                                                                      ]  16.73K  --.-KB/s    in 0.006s  

2023-06-04 13:36:04 (2.86 MB/s) - 'index.html' saved [17136]
```

## Test IPv6: Ingress

> via `NodePort`

```
root@node1:~# cat nginx.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
```

Now try accessing the `30080/tcp` over IPv6 address of your node.

## Additional verification

```
root@node1:~# calicoctl get node -o wide
NAME    ASN       IPV4              IPV6                    
node1   (64512)   65.108.6.185/26   2a01:4f9:6a:55d0::/64   

root@node1:~# calicoctl ipam show
+----------+------------------------------+-----------+------------+--------------+
| GROUPING |             CIDR             | IPS TOTAL | IPS IN USE |   IPS FREE   |
+----------+------------------------------+-----------+------------+--------------+
| IP Pool  | 10.233.64.0/18               |     16384 | 32 (0%)    | 16352 (100%) |
| IP Pool  | fd85:ee78:d8a6:8607::1:0/112 |     65536 | 30 (0%)    | 65506 (100%) |
+----------+------------------------------+-----------+------------+--------------+

root@node1:~# calicoctl ipam show --show-blocks --allow-version-mismatch
+----------+---------------------------------+-----------+------------+--------------+
| GROUPING |              CIDR               | IPS TOTAL | IPS IN USE |   IPS FREE   |
+----------+---------------------------------+-----------+------------+--------------+
| IP Pool  | 10.233.64.0/18                  |     16384 | 32 (0%)    | 16352 (100%) |
| Block    | 10.233.90.0/24                  |       256 | 32 (12%)   | 224 (88%)    |
| IP Pool  | fd85:ee78:d8a6:8607::1:0/112    |     65536 | 30 (0%)    | 65506 (100%) |
| Block    | fd85:ee78:d8a6:8607::1:a680/122 |        64 | 30 (47%)   | 34 (53%)     |
+----------+---------------------------------+-----------+------------+--------------+
```

```
root@node1:~# calicoctl ipam check
Checking IPAM for inconsistencies...

Loading all IPAM blocks...
Found 2 IPAM blocks.
 IPAM block 10.233.90.0/24 affinity=host:node1:
 IPAM block fd85:ee78:d8a6:8607::1:a680/122 affinity=host:node1:
IPAM blocks record 62 allocations.

Loading all IPAM pools...
  10.233.64.0/18
  fd85:ee78:d8a6:8607::1:0/112
Found 2 active IP pools.

Loading all nodes.
Found 1 node tunnel IPs.

Loading all workload endpoints.
Found 61 workload IPs.
Workloads and nodes are using 62 IPs.

Loading all handles
Looking for top (up to 20) nodes by allocations...
  node1 has 62 allocations
Node with most allocations has 62; median is 62

Scanning for IPs that are allocated but not actually in use...
Found 0 IPs that are allocated in IPAM but not actually in use.
Scanning for IPs that are in use by a workload or node but not allocated in IPAM...
Found 0 in-use IPs that are not in active IP pools.
Found 0 in-use IPs that are in active IP pools but have no corresponding IPAM allocation.

Scanning for IPAM handles with no matching IPs...
Found 0 handles with no matching IPs (and 32 handles with matches).
Scanning for IPs with missing handle...
Found 0 handles mentioned in blocks with no matching handle resource.
Check complete; found 0 problems.
```

- make sure `natOutgoing: true` for both `default-pool` and `default-pool-ipv6` IP pools

```
root@node1:~# calicoctl get ippools -o yaml
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2022-05-06T12:48:29Z"
    name: default-pool
    resourceVersion: "78112182"
    uid: bfe9ee79-1852-4e71-a8e1-901b47dac81b
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 24
    cidr: 10.233.64.0/18
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Always
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2023-06-04T06:04:06Z"
    name: default-pool-ipv6
    resourceVersion: "78125668"
    uid: 73e4db15-f8fa-405a-84e5-d5b345c0c524
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 122
    cidr: fd85:ee78:d8a6:8607::1:0/112
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
kind: IPPoolList
metadata:
  resourceVersion: "78168505"
```

### and some more snaps

```
# kubectl -n kube-system get daemonset calico-node -o yaml | grep -E -w -A1 'IP|IP_AUTODETECTION_METHOD|CALICO_IPV6POOL_CIDR|CALICO_ROUTER_ID|FELIX_IPV6SUPPORT|IP6|IP6_AUTODETECTION_METHOD|K8S_API_ENDPOINT'
        - name: FELIX_IPV6SUPPORT
          value: "True"
--
        - name: IP_AUTODETECTION_METHOD
          value: can-reach=$(NODEIP)
        - name: IP
          value: autodetect
        - name: IP6
          value: autodetect
```

```
root@node1:~# cat /etc/cni/net.d/10-calico.conflist 
{
  "name": "k8s-pod-network",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "datastore_type": "kubernetes",
      "nodename": "node1",
      "type": "calico",
      "log_level": "info",
      "log_file_path": "/var/log/calico/cni/cni.log",
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv6": "true",
        "ipv6_pools": ["fd85:ee78:d8a6:8607::1:0000/112"],
        "ipv4_pools": ["10.233.64.0/18"],
        "assign_ipv4": "true"
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type":"portmap",
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type":"bandwidth",
      "capabilities": {
        "bandwidth": true
      }
    }
  ]
}
```

**Comment by andy108369** [comment]
## MetalLB - IPv6 And Dual Stack Services

IPv6 technically worked on my Hetzner baremetal provider.

In practice it requires patching the service to allow the Ingress (the `PreferDualStack` `ipFamilyPolicy` and `IPv4/IPv6` `ipFamilies` -- see below).
And the netpol as well to allow the Egress (look for `patch netpol akash-deployment-restrictions` above).

This is something that akash-provider should be able to do, once it will officially support the IPv6 Dual Stack.

> **IPv6 And Dual Stack Services**
>
> IPv6 and dual stack services are supported in L2 mode, and in BGP mode only via the FRR mode.
>
> In order for MetalLB to allocate IPs to a dual stack service, there must be at least one address pool having both addresses of version v4 and v6.
>
> Note that in case of dual stack services, it is not possible to use spec.loadBalancerIP as it does not allow to request for multiple IPs, so the annotation metallb.universe.tf/loadBalancerIPs must be used.
> https://metallb.universe.tf/usage/


### metallb config

Here is the config that I've used in my setup:

> 65.108.6.186 & 65.108.6.187 -- IPs picked I do not control. They seem to have to be added as for the service to receive both IPv4 & IPv6 addresses. (I've tested a deployment with 2 leased IPs)

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 65.108.6.186/32
  - 65.108.6.187/32
  - 2a01:4f9:6a:55d0::/125
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
  namespace: metallb-system
```

### allow IPv4 & IPv6 ingress

```
kubectl patch svc ssh-ip-8022-tcp -n $ns --type='json' -p='[
  {"op": "replace", "path": "/spec/ipFamilyPolicy", "value": "PreferDualStack"},
  {"op": "replace", "path": "/spec/ipFamilies", "value": ["IPv4", "IPv6"]}
]'

kubectl patch svc ssh-ip-8080-tcp -n $ns --type='json' -p='[
  {"op": "replace", "path": "/spec/ipFamilyPolicy", "value": "PreferDualStack"},
  {"op": "replace", "path": "/spec/ipFamilies", "value": ["IPv4", "IPv6"]}
]'
```


```
root@node1:~/helm-charts# kubectl -n $ns get svc
NAME              TYPE           CLUSTER-IP      EXTERNAL-IP                        PORT(S)                         AGE
ssh-ip-8022-tcp   LoadBalancer   10.233.63.177   2a01:4f9:6a:55d0::,65.108.6.186    8022:32220/TCP                  4m13s
ssh-ip-8080-tcp   LoadBalancer   10.233.55.46    2a01:4f9:6a:55d0::1,65.108.6.187   8080:32265/TCP                  4m13s
ssh-np            NodePort       10.233.14.154   <none>                             8022:32036/TCP,8080:30357/TCP   4m13s
```

```
arno@x1:~$ curl -6 http://[2a01:4f9:6a:55d0::]:8080
curl: (7) Failed to connect to 2a01:4f9:6a:55d0:: port 8080 after 88 ms: Couldn't connect to server
arno@x1:~$ curl -6 -s http://[2a01:4f9:6a:55d0::1]:8080 | head -1
<!DOCTYPE html>
arno@x1:~$ ssh -p 22 root@2a01:4f9:6a:55d0:: "uname -n"
node1
arno@x1:~$ ssh -p 8022 root@2a01:4f9:6a:55d0:: "uname -n"
ssh-748dc4445-jflm6
```


![image](https://github.com/akash-network/support/assets/107317698/6608bae6-feaa-4e2b-af9d-9b97097ac4c3)


After the deployment with IPv6 - `akash-provider` `0.2.1` breaks with the following symptoms:
- `provider-services lease-status` hangs;
- closing the deployment (lease) does not free up the CPU/mem/storage resources until you restart `akash-provider` pod; (even despite the deployment gets successfully closed);
- provider sees new deployment order requests but isn't getting anywhere further than `requesting reservation`; (it also does report `order closed`, `shutting down` for the dseq when it is closed on the chain [and have never been actually deployed])


Initially, when I've added the `/64` range with **`18446744073709551615`** or `(2^64 - 1)` hosts  (`2a01:4f9:6a:55d0::/64`), the akash-provider read there are `9223372036854775808` available IPs.
I've then set it to `2a01:4f9:6a:55d0::/125` range so to have just **`7`** or `(2^3 - 1)` hosts.
But with that, the `akash-provider` pod broke until I lowered the IPv6 range:

```
I[2023-06-06|13:04:30.265] ip address inventory                         operator=ip in-use=0 available=9223372036854775808
```

```
provider error messsage:
ip operator remote error: http status 500 - unspecified error
```

**Comment by andy108369** [comment]
@troian as agreed during the last sig-support BiWeekly meeting here is the spec.
Please let me know if that's what you were expecting and if you have any questions.

----

# Technical Specification: Implementation of IPv6 Support in Akash Provider

## Overview

This specification outlines the steps to implement IPv6 support in Akash Provider. With the wide adoption of IPv6, it's important to have dual-stack capabilities for both internal and external networking to ensure Akash Provider can operate on networks with IPv6 support.

## Assumptions

    1. The hosting machine supports IPv6 and the network has been configured to use IPv6.
    2. The Akash Provider instance is running on Kubernetes and is managed using Kubespray.
    3. Netplan is being used for network configuration.
    4. You have administrative access to the cluster. (until Akash Provider updates the `akash-deployment-restrictions` ipBlock to the `::/0` IPV6 CIDR and patches the services's `ipFamilyPolicy => PreferDualStack & ipFamilies => IPv4, IPv6`)

## Implementation

1. Enable IPv6 Support on Host
Check if the hosting machine supports IPv6:

```
ls -la /proc/net/if_inet6
sysctl net.ipv6.conf.all.disable_ipv6 net.ipv6.conf.default.disable_ipv6 net.ipv6.conf.lo.disable_ipv6 net.ipv6.conf.all.forwarding net.ipv6.conf.default.forwarding
```

Example output:

```
# ls -la /proc/net/if_inet6
-r--r--r-- 1 root root 0 Jun  4 06:03 /proc/net/if_inet6

# sysctl net.ipv6.conf.all.disable_ipv6 net.ipv6.conf.default.disable_ipv6 net.ipv6.conf.lo.disable_ipv6 net.ipv6.conf.all.forwarding net.ipv6.conf.default.forwarding
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
net.ipv6.conf.all.forwarding = 1
net.ipv6.conf.default.forwarding = 1
```

2. Update Netplan Configuration
Obtain an IPv6 address from the ISP (e.g., `2a01:4f9:6a:55d0::/64`), and add it to the netplan configuration:

```
cat /etc/netplan/01.yaml
```

```
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
      dhcp4-overrides:
        use-domains: false
      # disable accept-ra, otherwise it will bring search domains to your /etc/resolv.conf
      # refs [https://bugs.launchpad.net/netplan/+bug/1858503](https://bugs.launchpad.net/netplan/+bug/1858503)
      accept-ra: false
      dhcp6: false
      addresses: 
        - 2a01:4f9:6a:55d0::/64
      gateway6: fe80::1
      routes:
      - to: ::/0
        via: fe80::1
        on-link: true
```

3. Update Kubespray Configuration
To enable IPv6, add the `enable_dual_stack_networks: true` to the `kubespray/inventory/akash/group_vars/k8s_cluster/k8s-cluster.yml` file.


4. Configure Calico for IPv6 NAT Outgoing
Add `nat_outgoing_ipv6: true` to `inventory/akash/group_vars/k8s_cluster/k8s-net-calico.yml`


5. Update Kubespray
Apply the Kubespray `facts.yml`, `upgrade-cluster.yml`, and `cluster.yml` playbooks in this order.


## Post-Implementation Adjustments

> Note that these adjustments (the `akash-deployment-restrictions` ipBlock to the `::/0` IPV6 CIDR update and the services's `ipFamilyPolicy => PreferDualStack & ipFamilies => IPv4, IPv6` patching) should be supported by the Akash Provider.

1. Update Network Policies

New deployments (or ones with an updated manifest) will receive an IPv6 address. However, the network policy egress should be updated to support the `::/0` IPV6 CIDR. For example:

```
kubectl -n $ns patch netpol akash-deployment-restrictions --type='json' -p='[{"op": "add", "path": "/spec/egress/-", "value": {"to": [{"ipBlock": {"cidr": "::/0"}}]}}]'
```

Note that if the `akash-provider` pod restarts, this command will need to be rerun.

2. Patch the Service

In order to accept Ingress over IPv6, the service needs to be patched as follows:

```
kubectl patch svc mixnode-np -n $ns --type='json' -p='[
  {"op": "replace", "path": "/spec/ipFamilyPolicy", "value": "PreferDualStack"},
  {"op": "replace", "path": "/spec/ipFamilies", "value": ["IPv4", "IPv6"]}
]'
```

## Test and Verification

Once the implementation has been completed, test and verify the setup by performing the following tests:
    1. Test IPv6 Egress: Use the wget command to access a known IPv6 address, such as Google.
    2. Test IPv6 Ingress: Deploy a simple service such as nginx and access it using the IPv6 address.
    3. Additional Verification: Check the allocations of IPs and check the IP pools using the `calicoctl` command.

## Risk and Mitigations

There might be potential issues with network latency and packet loss when adopting IPv6. Thorough testing should be done to ensure that these changes do not negatively affect the Akash Provider's performance. It's recommended to have a fallback plan to revert back to the IPv4 stack if any major issues are found during testing or production deployment.

----

# Technical Specification: Implementation of IPv6 Support in MetalLB

## Overview

This technical specification outlines the implementation of IPv6 and Dual Stack support in MetalLB (For IP Leasing offering). This enables MetalLB to operate in environments that use IPv6, IPv4 or both.

## Assumptions
    1. The Kubernetes cluster where MetalLB is deployed is running version 1.20 or later.
    2. The cluster has IPv6 enabled.
    3. You have administrative access to the cluster. (until Akash Provider does `ipFamilyPolicy => PreferDualStack & ipFamilies => IPv4, IPv6`)

## Implementation

1. Configure MetalLB for IPv6 and Dual Stack Services

MetalLB supports IPv6 and dual stack services in L2 mode and in BGP mode only via the FRR mode.
For MetalLB to allocate IPs to a dual stack service, there must be at least one address pool containing both v4 and v6 addresses.

MetalLB Configuration:

The configuration below should be placed in a file named `metallb-config.yaml`:

> This is an example configuration with known IPv4  IPv6 addresses.

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 65.108.6.186/32
  - 65.108.6.187/32
  - 2a01:4f9:6a:55d0::/125
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
  namespace: metallb-system
```

After creating the configuration, apply it using the following command:

```
kubectl apply -f metallb-config.yaml
```

3. Configure Service for IPv4 & IPv6 Ingress

> Note that these adjustments (`ipFamilyPolicy => PreferDualStack & ipFamilies => IPv4, IPv6`) should be supported by the Akash Provider.

To allow both IPv4 and IPv6 ingress, patch the services using the following commands:
```
kubectl patch svc ssh-ip-8022-tcp -n $ns --type='json' -p='[
  {"op": "replace", "path": "/spec/ipFamilyPolicy", "value": "PreferDualStack"},
  {"op": "replace", "path": "/spec/ipFamilies", "value": ["IPv4", "IPv6"]}
]'

kubectl patch svc ssh-ip-8080-tcp -n $ns --type='json' -p='[
  {"op": "replace", "path": "/spec/ipFamilyPolicy", "value": "PreferDualStack"},
  {"op": "replace", "path": "/spec/ipFamilies", "value": ["IPv4", "IPv6"]}
]'
```

## Test and Verification

After applying these configurations, test and verify the setup by checking if the services have received both IPv4 and IPv6 addresses. The following command should display these addresses:

```
kubectl -n $ns get svc
```

Example output:

```
NAME              TYPE           CLUSTER-IP      EXTERNAL-IP                        PORT(S)                         AGE
ssh-ip-8022-tcp   LoadBalancer   10.233.63.177   2a01:4f9:6a:55d0::,65.108.6.186    8022:32220/TCP                  4m13s
ssh-ip-8080-tcp   LoadBalancer   10.233.55.46    2a01:4f9:6a:55d0::1,65.108.6.187   8080:32265/TCP                  4m13s
ssh-np            NodePort       10.233.14.154   <none>                             8022:32036/TCP,8080:30357/TCP   4m13s
```

You can also verify if the services are reachable over IPv6 using curl for HTTP services and ssh for SSH services.

## Risks and Mitigations

IPv6 support in MetalLB might have some limitations due to underlying network conditions. It's crucial to perform thorough testing in a staging environment before implementing in a production setting. It is also recommended to have a fallback plan to revert back to IPv4-only mode if major issues arise during testing or after production deployment.
Please note, during initial tests, the provider may fail if there are too many hosts in an IPv6 pool. If this is the case, try using a narrower range to mitigate the issue. For example, changing /64 to /125 reduces the total number of available IPs, potentially avoiding a problem with the provider not handling a large number of IP addresses.

----

We can then use the `ipv6: <true|false>` provider attribute for the tenants to find it the provider that supports the IPv6.
