### ISSUE TITLE
SDL with GPU + no GPU deployment restarts akash-provider

### ISSUE THREAD

**Issue by zJuuu** [akash-network/support#104]
**Describe the bug**
SDL with GPU + no GPU deployment restarts akash-provider and all deployments.

SDL:
```
---
version: "2.0"

services:
  obtaingpu:
    image: ubuntu:22.04
    command:
      - "sh"
      - "-c"
    args:
      - 'uptime;
        nvidia-smi;
        sleep infinity'
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
  nogpu:
    image: ubuntu:22.04
    command:
      - "sh"
      - "-c"
    expose:
      - port: 8080
        as: 80
        to:
          - global: true

profiles:
  compute:
    obtaingpu:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
        storage:
          size: 1Gi
    nogpu:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    akash:
      pricing:
        obtaingpu: 
          denom: uakt
          amount: 10000000
        nogpu: 
          denom: uakt
          amount: 10000000

deployment:
  obtaingpu:
    akash:
      profile: obtaingpu
      count: 1
  nogpu:
    akash:
      profile: nogpu
      count: 1
```

**To Reproduce**
1. Deploy the sdl on your provider
2. Run kubectl get pods -A on your provider
3. See that the akash-provider restarted

**Expected behavior**
Deployment of SDL

**Additional context**
Provider Logs: https://transfer.sh/f7828tQGGg/provider-logs.tar.gz
