### ISSUE TITLE
Provider Fails to Withdraw Funds from Lease

### ISSUE THREAD

**Issue by chainzero** [akash-network/support#114]
Provider version - `v0.2.1`

**_Summary_**

Providers failing to initiate `wihdraw lease` transaction on small percentage of active leases.

**_Example of Issue_**

- Provider - akash18ga02jzaq8cw52anyhzkwta5wygufgu6zsz6xc
- DSEQ - 10561974
- Owner - akash1qyfg4zl2dku8ry7gjkhf88vnc3zrn6vmnzlvr9

When the lease state of this example, problem deployment is queried the escrow_payment > withdrawn > amount field is `0` despite the lease being active for several months.

```
provider-services query market lease get --dseq 10561974 --provider akash18ga02jzaq8cw52anyhzkwta5wygufgu6zsz6xc --owner akash1qyfg4zl2dku8ry7gjkhf88vnc3zrn6vmnzlvr9
escrow_payment:
  account_id:
    scope: deployment
    xid: akash1qyfg4zl2dku8ry7gjkhf88vnc3zrn6vmnzlvr9/10561974
  balance:
    amount: "0.000000000000000000"
    denom: uakt
  owner: akash18ga02jzaq8cw52anyhzkwta5wygufgu6zsz6xc
  payment_id: 1/1/akash18ga02jzaq8cw52anyhzkwta5wygufgu6zsz6xc
  rate:
    amount: "17.000000000000000000"
    denom: uakt
  state: open
  withdrawn:
    amount: "0"
    denom: uakt
lease:
  closed_on: "0"
  created_at: "10561981"
  lease_id:
    dseq: "10561974"
    gseq: 1
    oseq: 1
    owner: akash1qyfg4zl2dku8ry7gjkhf88vnc3zrn6vmnzlvr9
    provider: akash18ga02jzaq8cw52anyhzkwta5wygufgu6zsz6xc
  price:
    amount: "17.000000000000000000"
    denom: uakt
  state: active
  ```
  
 Majority of leases on this example provider are being withdrawn from properly and this issue only appears to occur on a very small subset of active leases.
  
 Have asked provider to collect logs from time period in which lease withdraws occur daily and will attach to issue once available.
 
 **Additional Examples**
 
-  Additional examples of zero withdraw issue can be found via:

`provider-services query market lease list --provider akash1p5vh8dsck7mnvc5zha6u3aes0fya3lq4ec9dpy --state active`

`provider-services query market lease get --dseq 12305281 --provider akash1lwzjtsqkuytusa98py77cflhqxl3z7v7ur5632 --owner akash1722lgxkjze280zv2gvhr05as9vsfm704yswj2l`

`provider-services query market lease get --dseq 11447603 --provider akash1tweev0k42guyv3a2jtgphmgfrl2h5y2884vh9d --owner akash1srujzhj2v9fkzhnn635udlczyhdpetuh34mhad`
