### ISSUE TITLE
Feature Request: support GPU selection based on additional resources (e.g. available VRAM)

### ISSUE THREAD

**Issue by andy108369** [akash-network/support#148]
> the feature was requested by Zach from Foundry in October 2023  
> I've tested the following on akash 0.26.1, provider 0.4.6.  

## Goal

Provider have 40gb a100's on the network and they are adding 80gb a100's too.
They're the same model but different VRAM.
They are wondering whether to just label everything a100-80gb or so?

# Implementation (PoC)

## CONFIG

- Node labels:

Label the worker node with `40Gi` & `80Gi` `a100`'s as follows:

```
akash.network/capabilities.gpu.vendor.nvidia.model.a100
akash.network/capabilities.gpu.vendor.nvidia.model.a100.40Gi
akash.network/capabilities.gpu.vendor.nvidia.model.a100.80Gi
```

- Update provider attributes (`provider.yaml`):

```
attributes:
...
  - key: capabilities/gpu/vendor/nvidia/model/a100
    value: true
  - key: capabilities/gpu/vendor/nvidia/model/a100/40Gi
    value: true
  - key: capabilities/gpu/vendor/nvidia/model/a100/80Gi
    value: true
```

- price target GPU mappings `provider.yaml` for `a100.40Gi`

```
price_target_gpu_mappings:  "a100=950,a100.40Gi=900,v100=350,rtx-8000=450,*=950"
```

SDL test for requesting `a100-40` GPU:

```
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: a100
                  ram: 40Gi
```

## TEST1

Provider thinks there is `insufficient capacity`:

```
D[2023-10-24|16:35:21.742] reservation requested                        module=provider-cluster cmp=provider cmp=service cmp=inventory-service order=akash1z6ql9vzhsumpvumj4zs8juv7l5u2zyr5yax2ys/13383046/1/1 resources[{resource:{id:1,cpu:{units:{val:1000}},memory:{size:{val:1073741824}},storage:[{name:default,size:{val:1073741824}}],gpu:{units:{val:1},attributes:[{key:vendor/nvidia/model/a100/40Gi,value:true}]},endpoints:[{kind:1,sequence_number:0},{sequence_number:0}]},count:1,price:{denom:uakt,amount:1000000.000000000000000000}}]=(MISSING)
I[2023-10-24|16:35:21.742] insufficient capacity for reservation        module=provider-cluster cmp=provider cmp=service cmp=inventory-service order=akash1z6ql9vzhsumpvumj4zs8juv7l5u2zyr5yax2ys/13383046/1/1
E[2023-10-24|16:35:21.742] reserving resources                          module=bidengine-order cmp=provider order=akash1z6ql9vzhsumpvumj4zs8juv7l5u2zyr5yax2ys/13383046/1/1 err="insufficient capacity"
```

Somehow the akash-provider reads `vendor/nvidia/model/a100/40Gi` (notice, `ram` isn't there) based on the following client SDL and attempts to evaluate `40Gi` as something it doesn't have (`value:true` ??) which is interesting:

```
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: a100
                  ram: 40Gi
```
