### ISSUE TITLE
refactor: remove bidengine pricing script and implement pricing strategy within bidengine module

### ISSUE THREAD

**Issue by troian** [akash-network/support#188]
### Is your feature request related to a problem? Please describe.

shell script is hard to maintain especially after introducing GPUs with various model/memory configurations

### Describe the solution you'd like

add `bidengine` section to provider config (to be completed by @troian)
```yaml
bidengine:
  addresses:
    whitelist:
    blacklist:
  pricing:
    cpu
    gpu:
    memory:
    storage:
```

### Describe alternatives you've considered

n/a

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
