### ISSUE TITLE
Enabling TLS Termination at the Pod level

### ISSUE THREAD

**Issue by cloud-j-luna** [akash-network/support#2]
I'm working on a feature to allow users of the Akash Network to specify that their deployments have TLS termination at the Pod level.

I have a working PoC and I'll submit a PR soon once I have tested everything locally. I'll also update this issue with relevant information and concerns regarding this approach.

**Comment by andy108369** [comment]
@cloud-j-luna just to clarify, this issue will include/cover the cert-manager (lets encrypt or a similar ACME compatible cert issuer) mentioned in https://github.com/akash-network/support/issues/3 ?

**Comment by cloud-j-luna** [comment]
Hey @andy108369 , just updated the issue. And no it does not include the cert-manager yet. This one allows users to manage their own certificates.

**Comment by troian** [comment]
makes sense on changes for `nginx-ingress`

```yaml
services:
  website:
    image: <image>
    env:
      - |
        TLS_CRT=${crt}
      - |
        TLS_KEY=${key}
    expose:
      - port: 443
        as: 80
        http_options:
          max_body_size: 104857600
        https_options:          # HERE
          ssl_passthrough: true # HERE
        to:
          - global: true
        accept:
          - ${full_domain}
```

SDL part tho needs some work.
1. I don't think creating a new section `https_options` makes sense as it creates ambivalent cases for properties like `max_body_size`. instead, it should be either within `http_options` or name the new section as `options`.
2. port configuration is another issue. in the example above TLS passthrough is actually done via port 80 and will not automatically redirect as this is a part of the backend service. Instead, it may look something like this:
   this example just shows configuration aspects of ports and ssl. there are other things to consider:
   - who sets redirect url
   - port 80 should not allow SSL traffic by default
   - etc

```yaml
services:
  website:
    image: <image>
    env:
      - |
        TLS_CRT=${crt}
      - |
        TLS_KEY=${key}
    expose:
      - port: 8080
        as: 80
        http_options:
          max_body_size: 104857600
          redirect_https: true # default false
        to:
          - global: true
        accept:
          - ${full_domain}
      - port: 8443
        as: 443
        http_options:
          max_body_size: 104857600
        options:
          ssl_passthrough: true # default false
        to:
          - global: true
        accept:
          - ${full_domain}
```
