### ISSUE TITLE
provider-services client: `http_options` limits are too strict, cannot set values beyond the defaults

### ISSUE THREAD

**Issue by andy108369** [akash-network/support#247]
The `read_timeout` is `60s` by [default](https://nginx.org/en/docs/ngx_mgmt_module.html#read_timeout),
and I cannot set it to a larger value as `provider-services` client exits with this error:

```
Error: http option not allowed: read timeout cannot be greater than 60000 ms
```

- SDL:
> changed `60` to `61` seconds
```
    expose:
      - port: 80
        as: 80
        to:
          - global: true
        accept:
          - api-andy1.beta.akashml.com
        http_options:
          read_timeout: 61000
```

I believe these limits are the same for the `send_timeout`, and `next_timeout` as well.

provider-services v0.6.2
