### ISSUE TITLE
UDP Support

### ISSUE THREAD

**Issue by Zblocker64** [akash-network/support#251]
### Is your feature request related to a problem? Please describe.

Yes. We can not currently request UDP ports.

### Describe the solution you'd like

Allow both TCP and UDP ports to be requested 

### Describe alternatives you've considered

Nothing can go around this as far as I know

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zblocker64** [comment]
SDL I am using

```
---
version: "2.0"
services:
  satisfactory-server:
    image: wolveix/satisfactory-server:latest
    expose:
      - port: 7777
        as: 7777
        proto: udp
        to:
          - global: true
    env:
      - SERVERGAMEPORT=7777
      - MAXPLAYERS=8
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    params:
      storage:
        data:
          mount: /config
          readOnly: false
profiles:
  compute:
    satisfactory-server:
      resources:
        cpu:
          units: 8
        memory:
          size: 32GB
        storage:
          - size: 10GB
          - name: data
            size: 15GB
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      pricing:
        satisfactory-server:
          denom: uakt
          amount: 100000
deployment:
  satisfactory-server:
    dcloud:
      profile: satisfactory-server
      count: 1
```


using `kubectl describe pod ...` this is the output of that container.

```
Containers:
  satisfactory-server:
    Container ID:   containerd://4e209da0b195a487f9e8148625851c2b38f1f30ae9ad5069687b180b416e5260
    Image:          wolveix/satisfactory-server:latest
    Image ID:       docker.io/wolveix/satisfactory-server@sha256:d5e93211f497369e90aa5404c268428f27c4e9db3485601a1b1265437fd02720
    Port:           7777/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 11 Sep 2024 08:10:15 -0500
    Ready:          True
```

Using my own provider to test

**Comment by Zblocker64** [comment]
Also tested with this SDL created by a member of the core team

```
---
version: "2.0"

services:
  softether:
    image: andrey01/softether:4.38-9760-2
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 992
        as: 992
        to:
          - global: true
      - port: 5555
        as: 5555
        to:
          - global: true
      - port: 1194
        as: 1194
        proto: udp
        to:
          - global: true
      - port: 500
        as: 500
        proto: udp
        to:
          - global: true
      - port: 4500
        as: 4500
        proto: udp
        to:
          - global: true

profiles:
  compute:
    softether:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        softether:
          denom: uakt
          amount: 10000

deployment:
  softether:
    akash:
      profile: softether
      count: 1
```

Result on provider side

```
Containers:
  softether:
    Container ID:   containerd://d2ad776f5357dadbd48c941c30ca82d502672b660d5f7fb8ef7a3830eb69e350
    Image:          andrey01/softether:4.38-9760-2
    Image ID:       docker.io/andrey01/softether@sha256:cacb7cca5598abe74dbb2370f9246d0def7dc85531ad56e322a5bd87426df5bb
    Ports:          80/TCP, 443/TCP, 500/TCP, 992/TCP, 1194/TCP, 4500/TCP, 5555/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Wed, 11 Sep 2024 08:14:08 -0500
    Ready:          True
```
