### ISSUE TITLE
Custom domains leading to the same ingress port

### ISSUE THREAD

**Issue by piber-dev** [akash-network/support#273]
**Describe the bug**
A user created a [report on Discord](https://discord.com/channels/747885925232672829/1111748832489910332/1326175966652792895) where he explained how when using the `accept` / `hosts` feature in SDL both lead to the external port 80 even though this was not specified from the beginning. I was able to recreate this with the following SDL where external ports 3001 and 3002 lead nowhere (as intended) but both the URIs created were mapped to external port 80 when one of them should have been pointed to external port 3001 and not lead anywhere. This is not the expected behavior from users and he was able to fix it by running some local commands on his own provider, but does not seem to be possible to do on Akash in its current form.

External port 3001: http://provider.europlots.com:31584/
External port 3002: http://provider.europlots.com:31626/
External port 80, mapped: port-80.ingress.europlots.com
External port 3001, mapped: qbrvo7b7vhernf1rpsglelmnn0.ingress.europlots.com

```
---
version: "2.0"
services:
  service-1:
    image: baktun/hello-akash-world:1.0.0
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
        accept:
          - port-80.ingress.europlots.com
      - port: 3001
        as: 3001
        to:
          - global: true
        accept:
          - port-3001.port-80.ingress.europlots.com
      - port: 3002
        as: 3002
        to:
          - global: true
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 1
        memory:
          size: 1GB
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 10000
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
```
