### ISSUE TITLE
Ingress and Dedicated IP Pod Conflict

### ISSUE THREAD

**Issue by pcfreak30** [akash-network/support#289]
**Describe the bug**

On K3S at-least (not tested on kubespray), you cannot have a dedicated ip pod (svc) and the ingress controller on the same node. Doing so will create port conflicts (80 and 443) and the dedicated ip service will never get created.

The only found workaround is the following:

```
controller:
  kind: DaemonSet
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containerPort:
    http: 30080
    https: 30443
  service:
    enabled: true
    type: ClusterIP
  ingressClassResource:
    name: "akash-ingress-class"
    default: false
  admissionWebhooks:
    enabled: true
    port: 7443
  config:
    allow-snippet-annotations: false
    compute-full-forwarded-for: true
    proxy-buffer-size: "16k"
    use-forwarded-headers: "true"
    proxy-real-ip-cidr: "0.0.0.0/0"
  metrics:
    enabled: true
  extraArgs:
    enable-ssl-passthrough: true
    http-port: 30080
    https-port: 30443
```

then add iptables rules to every node

```
-A PREROUTING -d EXTERNAL_NODE_IP -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 30080
-A PREROUTING -d EXTERNAL_NODE_IP -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 30443
-A PREROUTING -d EXTERNAL_NODE_IP -p tcp -m tcp --dport 8443 -j REDIRECT --to-ports 31443
-A PREROUTING -d EXTERNAL_NODE_IP -p tcp -m tcp --dport 8444 -j REDIRECT --to-ports 31444
-A OUTPUT -d 127.0.0.1/32 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 30080
-A OUTPUT -d 127.0.0.1/32 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 30443
-A OUTPUT -d 127.0.0.1/32 -p tcp -m tcp --dport 8443 -j REDIRECT --to-ports 31443
-A OUTPUT -d 127.0.0.1/32 -p tcp -m tcp --dport 8444 -j REDIRECT --to-ports 31444
-A POSTROUTING -s 172.17.0.0/16 ! -d 172.17.0.0/16 -j MASQUERADE
```

**To Reproduce**
1. Setup a k3s node wuth 1 worker using the new provider console
2. Setup metallb with atleast 1 IP
3. Create a deployment that takes that IP
4. Find the service for the pod (and maybe the pod itself) never gets scheduled?

**Expected behavior**
To be able to deploy the SDL properly.
