### ISSUE TITLE
ClusterIP access fails across nodes when ingress (netpol) uses Selectors (Calico iptables mode, K3s)

### ISSUE THREAD

**Issue by ghost** [akash-network/support#316]
**Summary:**

In a K3s cluster utilizing Calico as the CNI, we've observed that when a `NetworkPolicy` is applied with either a `namespaceSelector` or `podSelector` in the ingress rules, ClusterIP access to services fails **across nodes**. Notably, direct PodIP access remains functional, and ClusterIP access works when both pods reside on the same node.

**Reproducer:**

```bash
# 1. Create an isolated namespace
kubectl create ns nettest
kubectl label ns nettest test.network=isolated

# 2. Deploy nginx pod and service on node1
kubectl run nginx1 -n nettest --image=nginx:alpine \
  --overrides='{"spec":{"nodeName":"node1"}}' --port=80 \
  --labels="app=nginx" --expose

kubectl wait --for=condition=ready pod -l app=nginx -n nettest --timeout=60s

# 3. Retrieve ClusterIP and PodIP
CLUSTER_IP=$(kubectl get svc -n nettest nginx1 -o jsonpath='{.spec.clusterIP}')
POD_IP=$(kubectl get pod -n nettest -l app=nginx -o jsonpath='{.items[0].status.podIP}')

# 4. Test access from another node (node2)
kubectl run curl6 -n nettest --rm -i -t --restart=Never \
  --image=alpine \
  --overrides='{"spec":{"nodeName":"node2"}}' \
  -- sh -c "apk add -q curl && curl -v http://$POD_IP:80"   # ✅ Works

kubectl run curl6 -n nettest --rm -i -t --restart=Never \
  --image=alpine \
  --overrides='{"spec":{"nodeName":"node2"}}' \
  -- sh -c "apk add -q curl && curl -v http://$CLUSTER_IP:80"   # ❌ Fails (connection refused)
```

**NetworkPolicy Applied:**

```yaml
cat -<<EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-restrictions
  namespace: nettest
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          test.network: isolated
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
EOF
```

*Note:* Replacing `namespaceSelector` with `podSelector` yields the same result—ClusterIP access fails across nodes.

**Expected Behavior:**

Pods within the same namespace should be able to access services via ClusterIP, even when ingress rules use selectors.

**Actual Behavior:**

- ✅ Direct PodIP access works **across nodes**.
- ❌ ClusterIP access fails **across nodes** when ingress rules use `namespaceSelector` or `podSelector`. (NOTE: It works though without the selectors, i.e. when `ingress: [ { } ]` or netpol is removed)
- ✅ ClusterIP access succeeds when both pods are **on the same node**.

**Environment:**

- **K3s Version:** v1.30.6+k3s1
- **Containerd Version:** 1.7.22-k3s1
- **Calico Version:** v3.28.2
- **Akash Provider:** 0.6.11-rc1
- **Akash Node:** 0.38.2-rc0

**Additional Notes:**

- The `calico_backend` is set to `bird`, indicating the use of the standard Linux dataplane.
- `bpfEnabled` is set to `false` in the FelixConfiguration, confirming that eBPF mode is disabled.
- Despite eBPF being disabled, the issue persists, suggesting that the problem lies within the standard dataplane's handling of NetworkPolicy selectors for cross-node ClusterIP traffic.

**Comment by ghost** [comment]
**tl;dr:**

It appears that cross-node **ClusterIP access breaks when a NetworkPolicy controls ingress using `namespaceSelector` or `podSelector`**.  
However, it **works if you explicitly allow `ipBlock` set to the Calico IPPool CIDR** (e.g., `172.18.0.0/16`).

This likely happens because the **Pod IPs actually come from a different range (`10.42.0.0/16`)**, defined in the node `podCIDR`, which doesn't match the Calico IPPool's CIDR. As a result, **Calico can't reconcile selectors to the real Pod IPs**, breaking ingress across nodes.

----
**Long version**
ClusterIP cross-node access works when using `ipBlock`, but still fails with `podSelector` or `namespaceSelector` — even with Calico in bird/IPIP mode (`ipipMode: Always`, `vxlanMode: Never`) on `cidr: 172.18.0.0/16`.

**Details:**
✅ **Allowing ingress from `ipBlock: 172.18.0.0/16` works**.

❌ **Allowing from `namespaceSelector` or `podSelector` still breaks** for **cross-node** ClusterIP access.

This confirms the issue **is not specific to VXLAN or BPF modes** — it **still happens with Calico in bird/IPIP mode** (`ipipMode: Always`, `vxlanMode: Never`) on K3s clusters.

The root cause seems related to how **cross-node ClusterIP traffic is SNAT'ed**, which **hides the original Pod identity**, preventing `namespaceSelector` and `podSelector` based ingress rules from matching.  
However, `ipBlock` rules continue to work, because they are purely based on IP address ranges, not Pod or Namespace identity.

---

**Example of a working NetworkPolicy** (with IPBlock for your cluster):

> CIDR: `172.18.0.0/16` in this cluster example.
```bash
# kubectl get ippool default-ipv4-ippool -o jsonpath='{.spec.cidr}'; echo
172.18.0.0/16
```
> podCIDR: `10.42.0.0/24` - can be overridden by `--cluster-cidr=` param upon `k3s server ...` start; but it appears that it cannot be changed without the cluster rebuild from scratch ⚠ 
```bash
# kubectl get node -o jsonpath='{range .items[*]}{.metadata.name} {.spec.podCIDR}{"\n"}{end}'
node1 10.42.0.0/24
node2 10.42.1.0/24
```

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-restrictions
  namespace: nettest
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 172.18.0.0/16
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
```

**Comment by ghost** [comment]
https://github.com/projectcalico/calico/blob/v3.29.3/manifests/calico.yaml#L6288-L6292

```
            # The default IPv4 pool to create on startup if none exists. Pod IPs will be
            # chosen from this range. Changing this value after installation will have
            # no effect. This should fall within `--cluster-cidr`.
            # - name: CALICO_IPV4POOL_CIDR
            #   value: "192.168.0.0/16"
```
----
kubespray gets this set correctly out-of-box (but the k3s)
https://github.com/kubernetes-sigs/kubespray/blob/v2.26.0/docs/CNI/calico.md?plain=1#L63-L69
https://github.com/kubernetes-sigs/kubespray/blob/v2.26.0/roles/network_plugin/calico/tasks/install.yml#L88-L95
https://github.com/kubernetes-sigs/kubespray/blob/v2.26.0/roles/network_plugin/calico/tasks/install.yml#L227

![Image](https://github.com/user-attachments/assets/d7c15f12-fa74-458a-8b25-2143d02ee498)

i.e. if combining both kubespray & k3s terminologies:

The `calico_pool_cidr` (Kubespray parameter for Calico) must be fully contained within the `--cluster-cidr` (K3s server argument) or the `kube_pods_subnet` (Kubespray parameter for Kubernetes), to ensure Calico allocates pod IPs from the expected Kubernetes pod network range.

**Comment by ghost** [comment]
## k3s cluster build for reproducing the issue

> `node1` is the control-plane node, `node2` & `node3` - worker nodes
```
10.4.8.193 node1
10.4.8.194 node2
10.4.8.195 node3
```

1. Install k3s on `node1`
```
curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL="v1.32.3+k3s1" INSTALL_K3S_EXEC="--disable=traefik --flannel-backend=none --disable-network-policy --node-ip=10.4.8.193" sh -s -
mkdir ~/.kube
ln -svf /etc/rancher/k3s/k3s.yaml ~/.kube/config

command -v yq || curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq

curl -O https://raw.githubusercontent.com/projectcalico/calico/refs/tags/v3.29.3/manifests/calico.yaml
yq eval-all '(select(.kind == "DaemonSet" and .metadata.name == "calico-node").spec.template.spec.containers[] | select(.name == "calico-node").env) += {"name": "IP_AUTODETECTION_METHOD", "value": "kubernetes-internal-ip"}' -i calico.yaml

# can optionally "vim calico.yaml" to enable `container_settings allow_ip_forwarding` bits as per https://docs.k3s.io/networking/basic-network-options?cni=Calico#custom-cni

kubectl apply -f calico.yaml
```

2. Grab the k3s token from `node1`
```
cat /var/lib/rancher/k3s/server/token
```

3. Install and join k3s on the worker nodes (`node2` & `node3`)
```
curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL="v1.32.3+k3s1" K3S_URL=https://10.4.8.193:6443 K3S_TOKEN="K10f4ce80REDACTED::server:0f0516REDACTED8" sh -
```

4. Verify Calico CIDR & k3s POD CIDR
```
root@node1:~# kubectl get ippool default-ipv4-ippool -o jsonpath='{.spec.cidr}'; echo
192.168.0.0/16
root@node1:~# kubectl get node -o jsonpath='{range .items[*]}{.metadata.name} {.spec.podCIDR}{"\n"}{end}'
node1 10.42.0.0/24
node2 10.42.1.0/24
node3 10.42.3.0/24
```

5. Run the reproducer
Reproducer is in the original message of this issue. Make sure to apply the network policy for it to reproduce the issue. (!)

**Comment by ghost** [comment]
✅ **Confirmed root cause and fix**

The issue was caused by a mismatch between the Calico IPPool CIDR and the actual pod CIDRs assigned by K3s.

- Calico `IPPool` was originally set to `192.168.0.0/16` (default)
- K3s assigns podCIDRs like `10.42.0.0/24`, `10.42.1.0/24`, etc. (default; `10.42.0.0/16` & `10.43.0.0/16` are the default Pod & Service CIDRs in K3s, respectively)
- This broke **cross-node ClusterIP communication when network policies used `namespaceSelector` or `podSelector`**, but not when using `ipBlock` with the Calico pool CIDR.

🔍 The reason: **Pod IPs came from a range (`10.42.0.0/16`) outside the Calico IPPool**, so Calico couldn’t apply selector-based rules correctly.

---

✅ **Fix: Align Calico IPPool with K3s podCIDR**

```bash
kubectl patch ippool default-ipv4-ippool --type=merge -p '{"spec": {"cidr": "10.42.0.0/16"}}'
kubectl get pods -A -o wide | grep '192.168.' | awk '{print "kubectl delete pod -n "$1" "$2}' | sh
```

This reassigns pods with IPs in the correct range and **restores cross-node communication for selector-based network policies**.

**Comment by ghost** [comment]
## Extensive test

- Deploy `ingress-nginx` the same way Akash providers are running it
> Based on:
> https://akash.network/docs/other-resources/experimental/akash-provider-streamlined-build-with-rancher-k3s/#step-8---ingress-controller-install  
> https://akash.network/docs/providers/build-a-cloud-provider/akash-cli/akash-cloud-provider-build-with-helm-charts/#create-upstream-ingress-nginx-config  
```
wget https://get.helm.sh/helm-v3.17.3-linux-amd64.tar.gz
tar -zxvf helm-v3.17.3-linux-amd64.tar.gz
install linux-amd64/helm /usr/local/bin/helm
rm -rf linux-amd64 helm-v3.17.3-linux-amd64.tar.gz

cat >ingress-nginx-custom.yaml<<'EOF'
controller:
  service:
    type: ClusterIP
  ingressClassResource:
    name: "akash-ingress-class"
  kind: DaemonSet
  hostPort:
    enabled: true
  admissionWebhooks:
    port: 7443
  config:
    allow-snippet-annotations: false
    compute-full-forwarded-for: true
    proxy-buffer-size: "16k"
  metrics:
    enabled: true
  extraArgs:
    enable-ssl-passthrough: true
tcp:
  "8443": "akash-services/akash-provider:8443"
  "8444": "akash-services/akash-provider:8444"
EOF

helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
  --version 4.12.2 \
  --namespace ingress-nginx --create-namespace \
  -f ingress-nginx-custom.yaml
  
kubectl label ns ingress-nginx app.kubernetes.io/name=ingress-nginx app.kubernetes.io/instance=ingress-nginx
kubectl label ingressclass akash-ingress-class akash.network=true
```

- Create `nginx1` service in `nettest1` & `nettest2` namespaces:

```
for ns in nettest1 nettest2; do
  echo "### Setting up namespace: $ns"

  # 1. Create and label the isolated namespace
  kubectl create ns $ns --dry-run=client -o yaml | kubectl apply -f -
  kubectl label ns $ns test.network=isolated --overwrite
  kubectl label ns $ns akash.network/namespace=$ns --overwrite

  # 2. Deploy nginx as a Deployment pinned to node1, and expose as a ClusterIP service
  echo "  - Deploying nginx1 Deployment on node1"
  cat <<EOF | kubectl apply -n $ns -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
EOF

  echo "  - Creating nginx1 service"
  kubectl expose deployment nginx1 -n $ns --port=80 --target-port=80

  # Wait for the pod to be ready
  kubectl wait --for=condition=ready pod -l app=nginx -n $ns --timeout=60s

  # 3. Retrieve ClusterIP and PodIP
  CLUSTER_IP=$(kubectl get svc -n $ns nginx1 -o jsonpath='{.spec.clusterIP}')
  POD_IP=$(kubectl get pod -n $ns -l app=nginx -o jsonpath='{.items[0].status.podIP}')

  echo "  - Pod IP: $POD_IP"
  echo "  - Cluster IP: $CLUSTER_IP"

  # 4. Test access from another node (node2)
  echo "  - Testing access from node2 to PodIP (should succeed)"
  kubectl run curl-podip -n $ns --rm -i -t --restart=Never \
    --image=alpine \
    --overrides='{"spec":{"nodeName":"node2"}}' \
    -- sh -c "apk add -q curl && curl -sLI http://$POD_IP:80 | head -1"

  echo "  - Testing access from node2 to ClusterIP (should fail if Calico restricts inter-POD egress, say due to Calico IPPools vs K8s POD CIDR misalignmenet)"
  kubectl run curl-clusterip -n $ns --rm -i -t --restart=Never \
    --image=alpine \
    --overrides='{"spec":{"nodeName":"node2"}}' \
    -- sh -c "apk add -q curl && curl -sLI http://$CLUSTER_IP:80 | head -1"

  # 5. Apply updated NetworkPolicy
  echo "  - Applying updated NetworkPolicy"
  cat <<EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-restrictions
  namespace: $ns
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          akash.network/namespace: $ns
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
  - from:
    - namespaceSelector:
        matchLabels:
          test.network: isolated
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          akash.network/namespace: $ns
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/12
EOF

  # 6. Apply Ingress resource
  echo "  - Creating Ingress for $ns"
  cat <<EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx1-ingress
  namespace: $ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: akash-ingress-class
  rules:
  - host: nginx1.${ns}.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx1
            port:
              number: 80
EOF

done
```

- service to service test
```
kubectl run curl6 -n nettest1 --rm -i -t --restart=Never   --image=alpine   --overrides='{"spec":{"nodeName":"node1"}}'   -- sh -c "apk add -q curl && curl -v http://nginx1:80"

kubectl run curl6 -n nettest1 --rm -i -t --restart=Never   --image=alpine   --overrides='{"spec":{"nodeName":"node2"}}'   -- sh -c "apk add -q curl && curl -v http://nginx1:80"

kubectl run curl6 -n nettest2 --rm -i -t --restart=Never   --image=alpine   --overrides='{"spec":{"nodeName":"node3"}}'   -- sh -c "apk add -q curl && curl -v http://nginx1:80"
```

- pod to WAN test
```
kubectl -n nettest1 exec -i deploy/nginx1 -- sh -c "curl -sLI ident.me | head -1"
kubectl -n nettest2 exec -i deploy/nginx1 -- sh -c "curl -sLI ident.me | head -1"
```

- ingress tests (`10.4.8.193` is the node IP - `kubectl get nodes -o wide`):
```
curl -H "Host: nginx1.nettest1.test" http://10.4.8.193
curl -H "Host: nginx1.nettest2.test" http://10.4.8.193
```
