### ISSUE TITLE
Closed deployments still resolve via DNS on provider-basis

### ISSUE THREAD

**Issue by hard-nett** [akash-network/support#318]
**Assign the `support` label to any support escalation issues**

**Describe the bug**
I am able to make use of provider resources with multiple images while only paying for one. 
- account address = `akash1fxccvvhhy43tvet2ah7jqwq4cwl9k3dx3l2y8r`
- deployment sequence = `21419378`
- deploy.yaml:
```yaml
---
version: "2.0"
services:
  dnas:
    image: discoverdefiteam/dnas-sda:v0.0.3
    expose:
      - port: 3000
        as: 80
        accept:
          - dnas.permissionless.money
          - www.dnas.permissionless.money
          - infuse.permissionless.money
          - www.infuse.permissionless.money
        to:
          - global: true
    env:
      - NEXT_PUBLIC_DDNAS_API_BASE=https://pfpk.terpnetwork710.workers.dev
profiles:
  compute:
    dnas:
      resources:
        cpu:
          units: 4
        memory:
          size: 16GB
        storage:
          - size: 120GB
  placement:
    dcloud:
      pricing:
        dnas:
          denom: uakt
          amount: 10000
deployment:
  dnas:
    dcloud:
      profile: dnas
      count: 1

```

**To Reproduce**
1. Deploy a stale (previous) version of the intended image to a provider, setting DNS accepts
2. Route URI behind accepted DNS, confirm dns resolution works
3. Close instance
4. Deploy the current version. of the intended image to the same provider, setting DNS accepts to a new DNS as well as the previous DNS used in the instance  closed during the previous step.
5. Route the new URI to the new DNS, keeping the old URI configured to the old DNS endpoint (even though we defined the old DNS to now be accepted by the new URI)
6. Confirm that error is present & old DNS still resolves to the old image & renders the image we have closed, as well as the new image.

7. Attempt to resolve error by routing the old DNS to the new URI
8. Confirm old image still is resolved to old URI that should be closed, even after routing old DNS to new URI

**Expected behavior**
Once the instance is closed, DNS should never resolve the container on the provider
