### ISSUE TITLE
docs: metallb 0.13 uses CRD based config, docs need to reflect this

### ISSUE THREAD

**Issue by andy108369** [akash-network/support#74]
The docs should be updated => https://docs.akash.network/providers/build-a-cloud-provider/ip-leases-provider-enablement-optional-step/metallb-install

metallb 0.13 uses CRD-based config instead of the ConfigMap-based one, here are the migration steps => https://metallb.universe.tf/configuration/migration_to_crds/

# Migration steps

> based on https://metallb.universe.tf/configuration/migration_to_crds/

1. save the old v0.12 configmap-based metallb config to a `config.yaml` file
```
kubectl -n metallb-system get cm config -o yaml > config.yaml
```

2. use this command to migrate it to v0.13 (CRD-based format) - (`resources.yaml`)
```
docker run -d -v $(pwd):/var/input quay.io/metallb/configmaptocrs
```

This will produce a new config file - `resources.yaml`.

3. apply the new config
```
kubectl apply -f resources.yaml
```

4. remove the old config
```
kubectl -n metallb-system delete cm config
```

Now you can upgrade / use MetalLB v0.13.

# Example

## old v0.12 metallb configmap-based config

- `config.yaml`
```
apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 194.28.98.216/29
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config":"address-pools:\n- name: default\n  protocol: layer2\n  addresses:\n  - 194.28.98.216/29\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"config","namespace":"metallb-system"}}
  creationTimestamp: "2023-02-20T10:35:36Z"
  name: config
  namespace: metallb-system
  resourceVersion: "150026"
  uid: fd35767f-2f35-4792-b4fd-01b1d9ce2cb8
```

## new metallb v0.13 crd-based config

- `resources.yaml` file
```
# This was autogenerated by MetalLB's custom resource generator.
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  creationTimestamp: null
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 194.28.98.216/29
status: {}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  creationTimestamp: null
  name: l2advertisement1
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
status: {}
---
```

**Comment by andy108369** [comment]
The config examples for the docs are:

## MetalLB v0.12 config

> kubespray 2.21.0 brings metallb v0.12.1 by default https://github.com/kubernetes-sigs/kubespray/blob/v2.21.0/roles/download/defaults/main.yml#L1215

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 144.217.30.192/28
      - 198.50.185.112/28
      - 66.70.218.96/28
EOF
```


## MetalLB v0.13 config

```
cat <<EOF | kubectl apply -f -
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 144.217.30.192/28
  - 198.50.185.112/28
  - 66.70.218.96/28
  autoAssign: true
  avoidBuggyIPs: false
EOF
```
