### ISSUE TITLE
docs: add DNS configuration & verification steps to the docs

### ISSUE THREAD

**Issue by andy108369** [akash-network/support#80]
K8s DNS resolution breaks in pods when one uses DHCP / has bad DNS search domain is configured.

- all pods getting the DNS search domain from their `/etc/resolv.conf` file (kubelet does this);
- depending on the DNS search domains this can break the DNS resolution - DNS attempts would fail with `SERVFAIL` error (`host google.com`, `dig google.com`, `nslookup google.com`);
- it was rather tricky to figure why DNS search was still slipping through into the `/etc/resolv.conf` file;
- figured it was because `accept-ra` is enabled in the netplan by default => refs https://bugs.launchpad.net/netplan/+bug/1858503

The working netplan config:

```
root@node1:~# cat /etc/netplan/00-installer-config.yaml
# This is the network config written by 'subiquity'
network:
  version: 2
  renderer: networkd
  ethernets:
    ens160:
      dhcp4: true
      dhcp4-overrides:
        use-domains: false
      # disable accept-ra, otherwise it will bring search domains to your /etc/resolv.conf
      # refs https://bugs.launchpad.net/netplan/+bug/1858503
      accept-ra: false
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
        search: []

root@node1:~# netplan try
root@node1:~# netplan apply

root@node1:~# resolvectl domain ens160
Link 2 (ens160):

kubectl -n kube-system delete pods  --all
```

> Also worth checking what `Domains=` is set to in `/etc/systemd/resolved.conf` file on the host. Restart `systemd-networkd` & `systemd-resolved` services if necessary. Use `resolvectl domain`, `networkctl status | grep Search` to verify. Also `/run/systemd/network/10-netplan-eth0.network`, `grep DOMAINS /run/systemd/netif/state /run/systemd/netif/links/*`.

We should document this case and give users the verification steps so they can verify their DNS is working properly once they set up the K8s cluster.

## ~~Alternative fix~~

Provider owner can also change `dnsPolicy` from `Default` to `ClusterFirst` for the `coredns` deployment & `nodelocaldns` daemonset which will fix this behavior even when bad DNS search domain is present in the `/etc/resolv.conf` file:

```
kubectl patch deployment coredns -n kube-system --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/dnsPolicy", "value": "ClusterFirst"}]'
kubectl -n kube-system delete pods -l k8s-app=kube-dns

kubectl patch daemonset nodelocaldns -n kube-system --type=json -p='[{"op": "replace", "path": "/spec/template/spec/dnsPolicy", "value": "ClusterFirst"}]'
kubectl -n kube-system delete pods -l k8s-app=nodelocaldns
```

More about the `dnsPolicy` -> https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
Also worth reading https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
