### ISSUE TITLE
Make IP Lease available to deployment through ENV variable

### ISSUE THREAD

**Issue by anilmurty** [akash-network/support#84]
**Problem Statement**
Akash Network supports leasing IP addresses from providers that offer them but the leased IP is not easily accessible by the deployment. Having access to the IP lease from the deployment is important in cases where the deployment needs to use the IP address for communication once the application comes up. A good example of this is Kadena Nodes that need this info for communication. 

**Workaround**
The current workaround (in case of Kadena) is to read the IP address manually and build the application (Kadena node) by manually inserting the IP address at build time. 

** Suggested Solution **
The suggested solution is to improve user experience for tenants by exposing the IP lease to the deployment through an environment variable.

**Comment by anilmurty** [comment]
@boz @troian - please add context for where this code change should be made. From our discussion, I understand it is a relatively minor change that someone from the community (like @ PJEstrada) could potentially make.

**Comment by PJEstrada** [comment]
Hey guys, I started to read through the `ipOperator` code and `cluser` code. Giving the context I currently see this place where I can potentially add the new env variable for the IP.

https://github.com/akash-network/provider/blob/e7aa0b5b81957a130f1dc584f335c6f9e41db6b1/cluster/kube/builder/workload.go#L99

If this is the correct place, then what I'll need to figure out is to find a way to get the IP operators data, specifically the IP address string in the context of this function, so I can add it as part of the params to the `addEnvVarsForDeployment` .

 Does the `workload` object has any way to currently access this data? If you have any specific files that you suggest me to read more in detail I'll happily go though them.

Thanks a lot :)

**Comment by PJEstrada** [comment]
Thanks a lot @boz . I'll get back to you if I have any further questions.🙏

**Comment by PJEstrada** [comment]
Some related information regarding updating env variables on an already running deployment. Thanks to @andy108369 for sharing

Working POC to change a configmap without triggering a redeploy:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
data:
  VAR1: "value123"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: container1
    image: nginx
    volumeMounts:
    - name: cm1-vol
      mountPath: /etc/config
  volumes:
  - name: cm1-vol
    configMap:
      name: cm1
```

Shell excution:

```
root@node1:~# kubectl get cm cm1 -o json | jq -r '.data'
{
  "VAR1": "value123"
}

root@node1:~# kubectl exec -ti pod1 -- sh -c "cat /etc/config/VAR1" ; echo
value123

root@node1:~# kubectl edit cm cm1
configmap/cm1 edited

root@node1:~# kubectl get cm cm1 -o json | jq -r '.data'
{
  "VAR1": "value456"
}

root@node1:~# kubectl exec -ti pod1 -- sh -c "cat /etc/config/VAR1" ; echo
value123

root@node1:~# sleep 1m

root@node1:~# kubectl exec -ti pod1 -- sh -c "cat /etc/config/VAR1" ; echo
value456

```

**Comment by PJEstrada** [comment]
In terms of where to add the configmap creation, based on what I read so far, I believe we can add it on the handling of the events: 
```
ctypes.ProviderResourceAdd, ctypes.ProviderResourceUpdate:

```
https://github.com/akash-network/provider/blob/e7aa0b5b81957a130f1dc584f335c6f9e41db6b1/operator/ipoperator/ip_operator.go#L237

I see we have access to the `kube` client from the `ipoperator` so probably the way we could implement this is potentially calling the kube client to create the configmap. 

A couple questions I have:

1. The event has the service name available, however I believe we might need to attach the configmap to the deployments which are using the requested IP lease. Is this something we need to do beforehand, and is would it be OK to create a "default" configmap when creating deployments that require an IP lease?
2. If the configmap still does not exists, what would be the best place to create and attach this confimap as a volume? On the deployment creation?
3. Does the kube client offer any functionality as of now to update a configmap?

Thanks for the help :)

**Comment by boz** [comment]
Is it possible to not support updating the value for now?

**Comment by andy108369** [comment]
the `schedulingGates` that have been mentioned during today's call https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/

and the `readinessProbe` https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

my idea with the `readinessProbe` is that we could use something like this:

```
readinessProbe:
  exec:
    command:
    - <a shell command that would make a query against the akash-service to check whether the IP has been allocated for this particular deployment>
  initialDelaySeconds: 5
  periodSeconds: 5
```
