### ISSUE TITLE
Authorized Spend Not Returned To Grantee On Deployment Closure

### ISSUE THREAD

**Issue by chainzero** [akash-network/support#88]
Example Scenario:

Authorized spend is made from a grantor to a grantee of 10AKT.  Grantee creates deployment  using grant with 5AKT and closes deployment immediately,.  When authz grant balance is queried 5AKT (approx) is available.  The important point here is that when authz funds are used for a deployment - remaining funds left in escrow on close are not returned to the grant allocation.

```
###Authorization created

provider-services tx deployment authz grant akash12nwd3ezmfkux589wu47vsr3wd05kt9wn09ymgc 10000000uakt --from akash1f53fp8kk470f7k26yr5gztd9npzpczqv4ufud7

###State after initial authorization

provider-services query authz grants akash1f53fp8kk470f7k26yr5gztd9npzpczqv4ufud7 akash12nwd3ezmfkux589wu47vsr3wd05kt9wn09ymgc
grants:
- authorization:
    '@type': /akash.deployment.v1beta2.DepositDeploymentAuthorization
    spend_limit:
      amount: "10000000"
      denom: uakt
  expiration: "2023-11-26T14:28:36Z"
pagination:
  next_key: null
  total: "0"

  ###Deployment created using authorization and then immediately closed

  provider-services tx deployment create --depositor-account akash1f53fp8kk470f7k26yr5gztd9npzpczqv4ufud7 --from akash12nwd3ezmfkux589wu47vsr3wd05kt9wn09ymgc deploy.yml -y 

provider-services tx deployment close --from $AKASH_KEY_NAME

###Balance of authorization after closure (as we can see the auth is now 5AKT in balance

root@ip-172-31-41-158:~# provider-services query authz grants akash1f53fp8kk470f7k26yr5gztd9npzpczqv4ufud7 akash12nwd3ezmfkux589wu47vsr3wd05kt9wn09ymgc
grants:
- authorization:
    '@type': /akash.deployment.v1beta2.DepositDeploymentAuthorization
    spend_limit:
      amount: "5000000"
      denom: uakt
  expiration: "2023-11-26T14:28:36Z"
  ```
